name: Daily llama.cpp build (ggml)

on:
  workflow_dispatch:
    inputs:
      llamacpp_tag:
        description: "llama.cpp tag to build (empty = latest)"
        required: false
        default: ""
  schedule:
    - cron: "0 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - rocm_version: "7.14"
            llamacpp_tag: "${{ inputs.llamacpp_tag }}"
            release_tag: "20260808180342"
          #- rocm_version: "6.3.3"
          #  llamacpp_tag: "${{ inputs.llamacpp_tag }}"
          #  release_tag: "20260808180342"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          ref: ${{ matrix.build.release_tag }}

      - name: Aggressive cleanup
        uses: ./.github/workflows/actions/cleanup-space-action

      - name: Install yq
        uses: ./.github/workflows/actions/install-yq-action

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run build script
        env:
          LLAMA_REPO: "https://github.com/ggml-org/llama.cpp.git"
          LLAMA_ROCM_VERSION: "${{ matrix.build.rocm_version }}"
          LLAMA_BRANCH: "${{ matrix.build.llamacpp_tag }}"
          LLAMA_IS_RELEASE: "1"
          LLAMA_CMAKE_HIP_FLAGS: "-mllvm -amdgpu-sched-strategy=max-ilp"
          GITHUB_TOKEN: "${{ github.token }}"
        run: |
          cd ./llama.cpp
          if [ "$LLAMA_BRANCH" == "" ]; then
            LLAMA_BRANCH="$("$GITHUB_WORKSPACE/.github/scripts/github_get_last" --type release --repo "$LLAMA_REPO" --github-token "$GITHUB_TOKEN")"
            export LLAMA_BRANCH
          fi
          export LLAMA_PRESET_NAME="${LLAMA_BRANCH}-rocm-${LLAMA_ROCM_VERSION}"
          ./build-and-push.image.sh
