name: Build ROCm TransferBench DEB

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "**"
    paths:
      - "rocm-transfer-bench/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - rocm_version: "7.14"
            tb_version: "v1.69.01"
    steps:
      - uses: actions/checkout@v7

      - name: Build DEB package
        working-directory: rocm-transfer-bench
        run: |
          export ROCM_VERSION="${{ matrix.build.rocm_version }}"
          export TB_VERSION="${{ matrix.build.tb_version }}"
          export TB_PUSH=0
          ./build-and-push.deb.sh

      - name: Upload DEB package
        uses: actions/upload-artifact@v6
        with:
          name: rocm-transfer-bench-${{ matrix.build.tb_version }}-rocm-${{ matrix.build.rocm_version }}-deb
          path: rocm-transfer-bench/output/**/*.deb
          if-no-files-found: error
          retention-days: 14
# re-register
